/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.awt.Color;
import java.awt.Component;
import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import static javafx.scene.input.KeyCode.T;
import javax.swing.JButton;

/**
 *
 * @author jhon doe
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String[] sim={"1","5","10","50","100","250","500","1000","5000","20000","50000","75000","100000"};
    
    int[] index={ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int iter=0;
    int sum=0;
    public NewJFrame() {
        initComponents();     
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(false);
            }
        setLocationRelativeTo(null);
        jButton31.setVisible(false);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("1");
        buttonGroup1.add(jButton1);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        buttonGroup1.add(jButton2);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("3");
        buttonGroup1.add(jButton3);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("4");
        buttonGroup1.add(jButton4);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("5");
        buttonGroup1.add(jButton5);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("6");
        buttonGroup1.add(jButton6);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        buttonGroup1.add(jButton7);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("8");
        buttonGroup1.add(jButton8);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("9");
        buttonGroup1.add(jButton9);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("10");
        buttonGroup1.add(jButton10);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("11");
        buttonGroup1.add(jButton11);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setText("12");
        buttonGroup1.add(jButton12);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setText("13");
        buttonGroup1.add(jButton13);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jLabel3.setText("Select a number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(44, 44, 44))
        );

        jButton25.setText("?");
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });

        jButton26.setText("?");
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton26MouseClicked(evt);
            }
        });
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("?");
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton27MouseClicked(evt);
            }
        });

        jButton28.setText("?");
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });

        jButton29.setText("?");
        jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton29MouseClicked(evt);
            }
        });

        jButton30.setText("?");
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton30MouseClicked(evt);
            }
        });

        jButton21.setText("?");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });

        jButton22.setText("?");
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });

        jButton23.setText("?");
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton23MouseClicked(evt);
            }
        });

        jButton24.setText("?");
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton24MouseClicked(evt);
            }
        });

        jButton15.setText("?");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jButton20.setText("?");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });

        jButton14.setText("?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton22)
                    .addComponent(jButton23)
                    .addComponent(jButton24)
                    .addComponent(jButton20)
                    .addComponent(jButton15)
                    .addComponent(jButton21))
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton30, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton29, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton27, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton28, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton25, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton26)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButton14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20)
                    .addComponent(jButton26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21)
                    .addComponent(jButton27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton22)
                    .addComponent(jButton28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23)
                    .addComponent(jButton29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton24)
                    .addComponent(jButton30))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton32.setText("Deal");
        jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton32MouseClicked(evt);
            }
        });

        jButton33.setText("No Deal");
        jButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton33MouseClicked(evt);
            }
        });

        jButton31.setText("Play again!");
        jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton31MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(jButton31))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton32)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton33))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton32)
                    .addComponent(jButton33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton31)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jPanel1.setVisible(false);
        jButton14.setText("1");
        jButton15.setText("2");
        jButton20.setText("3");
        jButton21.setText("4");
        jButton22.setText("5");
        jButton23.setText("6");
        jButton24.setText("7");
        jButton25.setText("8");
        jButton26.setText("9");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");       
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
Collections.shuffle(Arrays.asList(sim));
jButton14.setBackground(Color.red);jButton14.setEnabled(false);
jButton14.setForeground(Color.green);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jPanel1.setVisible(false);
        jButton14.setText("2");
        jButton15.setText("1");
        jButton20.setText("3");
        jButton21.setText("4");
        jButton22.setText("5");
        jButton23.setText("6");
        jButton24.setText("7");
        jButton25.setText("8");
        jButton26.setText("9");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");      
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);
        jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("3");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("4");
        jButton22.setText("5");
        jButton23.setText("6");
        jButton24.setText("7");
        jButton25.setText("8");
        jButton26.setText("9");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");   
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);
        jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("4");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("5");
        jButton23.setText("6");
        jButton24.setText("7");
        jButton25.setText("8");
        jButton26.setText("9");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");  
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("5");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("6");
        jButton24.setText("7");
        jButton25.setText("8");
        jButton26.setText("9");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");   
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("6");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("5");
        jButton24.setText("7");
        jButton25.setText("8");
        jButton26.setText("9");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");   
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("7");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("5");
        jButton24.setText("6");
        jButton25.setText("8");
        jButton26.setText("9");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");     
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("8");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("5");
        jButton24.setText("6");
        jButton25.setText("7");
        jButton26.setText("9");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");  
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("9");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("5");
        jButton24.setText("6");
        jButton25.setText("7");
        jButton26.setText("8");
        jButton27.setText("10");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");    
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("10");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("5");
        jButton24.setText("6");
        jButton25.setText("7");
        jButton26.setText("8");
        jButton27.setText("9");
        jButton28.setText("11");
        jButton29.setText("12");
        jButton30.setText("13");  
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("11");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("5");
        jButton24.setText("6");
        jButton25.setText("7");
        jButton26.setText("8");
        jButton27.setText("9");
        jButton28.setText("10");
        jButton29.setText("12");
        jButton30.setText("13");  
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("12");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("5");
        jButton24.setText("6");
        jButton25.setText("7");
        jButton26.setText("8");
        jButton27.setText("9");
        jButton28.setText("10");
        jButton29.setText("11");
        jButton30.setText("13");  
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
jPanel1.setVisible(false);        // TODO add your handling code here:
jButton14.setText("13");
        jButton15.setText("1");
        jButton20.setText("2");
        jButton21.setText("3");
        jButton22.setText("4");
        jButton23.setText("5");
        jButton24.setText("6");
        jButton25.setText("7");
        jButton26.setText("8");
        jButton27.setText("9");
        jButton28.setText("10");
        jButton29.setText("11");
        jButton30.setText("12");  
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        Collections.shuffle(Arrays.asList(sim));
        jButton14.setBackground(Color.red);jButton14.setEnabled(false);jButton14.setForeground(Color.green);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        index[0]=1;
        jButton15.setText(sim[0]);        
        jButton15.setBackground(Color.red);jButton15.setForeground(Color.red);
jButton14.setBackground(Color.red);
        jButton15.setEnabled(false);jButton14.setEnabled(false);
        
        iter++;
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            } 
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton32MouseClicked
        // TODO add your handling code here:
        jLabel2.setText("WOW! You won $"+sum);
        jLabel1.setText("");
        jButton31.setVisible(true);
        
    }//GEN-LAST:event_jButton32MouseClicked

    private void jButton33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton33MouseClicked
        // TODO add your handling code here:
        Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                if(component[i].getBackground()!=Color.red)
                 component[i].setEnabled(true);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(false);
            } 
            
    }//GEN-LAST:event_jButton33MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        iter++; index[1]=1;
        jButton20.setText(sim[1]);        jButton14.setBackground(Color.red);
        jButton20.setBackground(Color.red); jButton20.setForeground(Color.red);

         jButton20.setEnabled(false);
        jButton14.setEnabled(false);
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            }if(sum==max/3) {
                max+=100;
            }  
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {
                jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }
    }//GEN-LAST:event_jButton20MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
iter++;index[2]=1;jButton21.setText(sim[2]);        jButton14.setBackground(Color.red);
        jButton21.setBackground(Color.red);jButton21.setForeground(Color.red);

 jButton21.setEnabled(false);
        jButton14.setEnabled(false);
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            }  
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
iter++;index[3]=1;jButton22.setText(sim[3]);        jButton14.setBackground(Color.red);
        jButton22.setBackground(Color.red);jButton22.setForeground(Color.red);

 jButton22.setEnabled(false);
        jButton14.setEnabled(false);
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            }if(sum==max/3) {
                max+=100;
            }  
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
iter++;index[4]=1;jButton23.setText(sim[4]);        jButton14.setBackground(Color.red);
        jButton23.setBackground(Color.red);jButton23.setForeground(Color.red);

 jButton23.setEnabled(false);
        jButton14.setEnabled(false);
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            }  
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23MouseClicked

    private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
iter++;index[5]=1;jButton24.setText(sim[5]);        jButton14.setBackground(Color.red);
        jButton24.setBackground(Color.red);jButton24.setForeground(Color.red);

 jButton24.setEnabled(false);
        jButton14.setEnabled(false);
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            }  
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24MouseClicked

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
iter++;index[6]=1;jButton25.setText(sim[6]);        jButton14.setBackground(Color.red);
        jButton25.setBackground(Color.red);jButton25.setForeground(Color.red);

 jButton25.setEnabled(false);
        jButton14.setEnabled(false);
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            } 
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25MouseClicked

    private void jButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseClicked
iter++;index[7]=1;jButton26.setText(sim[7]);        jButton14.setBackground(Color.red);
        jButton26.setBackground(Color.red);jButton26.setForeground(Color.red);

 jButton26.setEnabled(false);
        jButton14.setEnabled(false);
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            } 
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26MouseClicked

    private void jButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseClicked
iter++;index[8]=1;jButton27.setText(sim[8]);jButton14.setBackground(Color.red);jButton27.setBackground(Color.red);
 jButton27.setEnabled(false);jButton27.setForeground(Color.red);
        
        jButton14.setEnabled(false);
        
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            } 
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27MouseClicked

    private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
iter++;index[9]=1;jButton28.setText(sim[9]);jButton14.setBackground(Color.red);jButton28.setBackground(Color.red);
 jButton28.setEnabled(false);jButton28.setForeground(Color.red);
        
        jButton14.setEnabled(false);
        
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            }  
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28MouseClicked

    private void jButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseClicked
iter++;index[10]=1;jButton29.setText(sim[10]);jButton14.setBackground(Color.red);jButton29.setBackground(Color.red);
 jButton29.setEnabled(false);jButton29.setForeground(Color.red);
        
        jButton14.setEnabled(false);
        
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            } 
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29MouseClicked

    private void jButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseClicked
iter++;index[11]=1;jButton30.setText(sim[11]);jButton14.setBackground(Color.red);jButton30.setBackground(Color.red);
 jButton30.setEnabled(false);jButton30.setForeground(Color.red);
        
        jButton14.setEnabled(false);
        
        if(iter>=6) {
            Component[] component = jPanel2.getComponents(); 
            for(int i=0; i<component.length; i++) {
                 component[i].setEnabled(false);
            }
            Component[] component1 = jPanel3.getComponents(); 
            for(int i=0; i<component1.length; i++) {
                 component1[i].setEnabled(true);
            } 
            int max=0;
            for(int i=0;i<13;i++) {
                if(index[i]==1) {
                    int xx=Integer.parseInt(sim[i]);
                    max+=(xx)/2;
                }
            } if(sum==max/3) {
                max+=100;
            }  
            jLabel1.setText("Deal for amt $"+max/3); sum=max/3;
            if(iter==11) {jPanel2.setEnabled(false);
            int ma[] = {0,0};
            for(int i=0;i<13;i++) {
                if(index[i]==0) {
                    int xx=Integer.parseInt(sim[i]);
                    if(ma[0]==0) ma[0]=xx;
                    if(ma[1]==0) ma[1]=xx;
                }
            } 
            Collections.shuffle(Arrays.asList(ma));
            jLabel2.setText("WOW! You won $"+ma[0]);
        jLabel1.setText("");
        jButton31.setVisible(true);
        }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30MouseClicked

    private void jButton31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton31MouseClicked
      jLabel1.setText(""); jLabel2.setText("");
      jPanel2.setVisible(false);
      jPanel3.setVisible(false);
      jPanel1.setVisible(true);
      jButton31.setVisible(false);
      jButton15.setForeground(Color.black);
      jButton20.setForeground(Color.black);
      jButton21.setForeground(Color.black);
      jButton22.setForeground(Color.black);
      jButton23.setForeground(Color.black);
      jButton24.setForeground(Color.black);
      jButton25.setForeground(Color.black);
      jButton26.setForeground(Color.black);
      jButton27.setForeground(Color.black);
      jButton28.setForeground(Color.black);
      jButton29.setForeground(Color.black);
      jButton30.setForeground(Color.black);
      
      jButton15.setBackground(null);
      jButton20.setBackground(null);
      jButton21.setBackground(null);
      jButton22.setBackground(null);
      jButton23.setBackground(null);
      jButton24.setBackground(null);
      jButton25.setBackground(null);
      jButton26.setBackground(null);
      jButton27.setBackground(null);
      jButton28.setBackground(null);
      jButton29.setBackground(null);
      jButton30.setBackground(null);
      jButton32.setEnabled(false);
      jButton33.setEnabled(false);
      iter=0;
      jButton15.setEnabled(true);
      jButton20.setEnabled(true);
      jButton21.setEnabled(true);
      jButton22.setEnabled(true);
      jButton23.setEnabled(true);
      jButton24.setEnabled(true);
      jButton25.setEnabled(true);
      jButton26.setEnabled(true);
      jButton27.setEnabled(true);
      jButton28.setEnabled(true);
      jButton29.setEnabled(true);
      jButton30.setEnabled(true);
    }//GEN-LAST:event_jButton31MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
